---
name: Test
on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment: test
    env:
      GITHUB_TOKEN: "test-token"
      REDIS_URL: "redis://:redispassword@localhost:6379"
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Set up Go 1.24
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'

    - name: Start services
      run: docker compose -f docker-compose.test.yml up -d

    - name: Build
      run: make build

    - name: Test
      run: make build
